name: General

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get .
      - name: Build project
        run: go build -v ./...
      - name: Test project
        run: go test
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Check fmt
        run: test -z $(gofmt -l .)
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
